version: '3'
services:
  node-app:
    build: node-app
    restart: always
  traefik:
    image: traefik:alpine
    volumes:
      - ./config:/config
    depends_on:
      - node-app
    links:
      - node-app
    ports:
      - "${PORT:-80}:80"
      - "${PORT:-443}:443"
    restart: always
    command: traefik --configfile=/config/traefik.toml
