defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "jon@gomagames.com"
storage = "/config/acme.json"
entryPoint = "https"
acmeLogging = true
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

[[acme.domains]]
  main = "test1.lawnchairship.com"
[[acme.domains]]
  main = "test2.lawnchairship.com"
[[acme.domains]]
  main = "test3.lawnchairship.com"

[acme.httpChallenge]
  entryPoint = "http"

[file]

[frontends]
  [frontends.frontend1]
  backend = "node-backend"
  passHostHeader = true

[backends]
  [backends.node-backend]
    [backends.node-backend.servers.server1]
    url = "http://node-app:3000"
